conversions:
  drawio:
    - input: ./MixerIEMRack/WiringDiagram.drawio
      png: ./../Assets/MixerIEMRack/
    - input: ./Stage Diagram/FullBand/StageDiagram.drawio
      png: ./../../Assets/StageDiagram/FullBand/
      pdf: ./../../Assets/StageDiagram/FullBand/
    - input: ./Trailer/TrailerLoadMap.drawio
      png: ./../Assets/Trailer/
      pdf: ./../Assets/Trailer/
  excel:
    - input: ./BandColorConvention/BandColorConvention.xlsx
      sheet: 'Document Style'
      topLeftCell: 'A1'
      bottomRightCell: 'E7'
      png: ./../Assets/BandColorConvention/
    - input: ./InputList/Acoustic/InputList.xlsx
      sheet: 'Channels'
      topLeftCell: 'A1'
      bottomRightCell: 'H19'
      pdf: ./../../Assets/InputList/Acoustic/
    - input: ./InputList/FullBand/InputList.xlsx
      sheet: 'Channels'
      topLeftCell: 'A1'
      bottomRightCell: 'I43'
      png: ./../../Assets/InputList/FullBand/
      pdf: ./../../Assets/InputList/FullBand/
    - input: ./InputList/FullBand/SplitMap.xlsx
      sheet: 'Split Map'
      topLeftCell: 'A1'
      bottomRightCell: 'Q8'
      pdf: ./../../Assets/InputList/FullBand/
